import {chocolatedonut,
  strawberrydonut,
  omelette,
  waffle,
  sandwich,
  croissant,
  pancake,
  baconSandwich,
  greekSalad,
  lemonCake} from '../../assests/breakfast imgs';
  import {bbqRibs,
    bbqchickenpizza,
    vegpizza,
    fishandchips,
    fruitSalad,
    hotdog,
    lemonrosemary,
    lemonPudding,
    margheritaPizza,
    mexicantacos,
    pasta,
    pepperonipizza,
    ranchporkroast,
    steak} from '../../assests/dinner imgs';
import {chickenTacos,
  californiaroll,
  bruschetta,
  buffalowings,
  cobbsalad,
  keylimepie,
  lasagana,
  steakfajita,vegtacos} from '../../assests/lunch imgs';
import {expresso,
  latte,
  avacado,
  banana,blueberry,
  strawberry,
  dragonfruit,
  kiwi} from '../../assests/drinks';
const Dishes = [
  {
    id: 1,
    title: 'Chocolate Donut',
    category: 'breakfast',
    price:7.99,
    img: chocolatedonut,
    desc: `Indulge in a little bit of heaven with our Chocolate Donut - a delectable treat that's a chocolate lover's dream come true! `,
  },
  {
    id: 2,
    title: 'Pancakes with honey and berries',
    category: 'breakfast',
    price: 15.99,
    img: pancake,
    desc: `Sweeten up your morning with our Honey Berry Pancakes! `,
  },
  {
    id: 3,
    title: 'strawberry donut',
    category: 'breakfast',
    price: 7.99,
    img: strawberrydonut,
    desc: `Treat yourself to a burst of sweetness with our Strawberry Donut - a delectable and colorful pastry that's perfect for satisfying your sweet tooth cravings! `,
  },
  {
    id: 4,
    title: 'omelette',
    category: 'breakfast',
    price: 7.99,
    img:omelette,
    desc: `Fuel up with our Omelette - a protein-packed breakfast masterpiece that's customizable to your taste buds and cooked to perfection! `,
  },
  {
    id: 5,
    title: 'Waffles with honey and berries ',
    category: 'breakfast',
    price: 15.99,
    img: waffle,
    desc: `Indulge in a sweet sensation with our Honey Berry Waffles - a deliciously fluffy and crispy breakfast treat 
    that's topped with luscious berries and drizzled with golden honey! `,
  },
  {
    id: 6,
    title: ' Ham Sandwiches',
    category: 'breakfast',
    price: 8.99,
    img: sandwich,
    desc: `Enjoy a classic: our Ham Sandwich `,
  },
  {
    id: 7,
    title: 'Crossiant',
    category: 'breakfast',
    price: 6.99,
    img: croissant,
    desc: `Indulge in a taste of Paris with our Croissant - a buttery and flaky pastry that's perfect for breakfast, brunch, or any time you crave a touch of French sophistication `,
  },
  {
    id: 8,
    title: 'Bacon Sandwich',
    category: 'breakfast',
    price: 7.99,
    img:baconSandwich,
    desc: `Start your day off right with our Bacon Sandwich - a mouthwatering and savory delight that's the perfect breakfast, lunch, or anytime snack! `,
  },
  {
    id: 9,
    title: 'Greek Salad',
    category: 'breakfast',
    price: 7.99,
    img:greekSalad,
    desc: `Get a taste of the Mediterranean with our Greek Salad - a refreshing and healthy mix of crisp veggies, 
    tangy feta cheese, and flavorful olives that's simply irresistible! `,
  },
  {
    id: 10,
    title: 'Lemon Cake',
    category: 'breakfast',
    price: 7.99,
    img:lemonCake,
    desc: `Indulge in a slice of sunshine with our Lemon Cake - a moist and zesty dessert that's bursting with citrus flavor and guaranteed to brighten your day! `,
  },
  {
    id: 11,
    title: 'BBQ Ribs',
    category: 'Dinner',
    price: 25.99,
    img:bbqRibs,
    desc: `Fall-off-the-bone goodness awaits with our BBQ Ribs - a mouthwatering and finger-licking feast that's sure to leave you wanting more! `,
  },
  {
    id: 12,
    title: 'BBQ Chicken Pizza',
    category: 'Dinner',
    price: 18.99,
    img:bbqchickenpizza,
    desc: `Satisfy your hunger with our BBQ Chicken Pizza - a smoky and savory sensation that's packed with juicy chicken, tangy BBQ sauce, and melted cheese! `,
  },
  {
    id: 13,
    title: 'veg pizza',
    category: 'Dinner',
    price: 15.99,
    img:vegpizza,
    desc: `Experience a slice of heaven with our Veggie Pizza - a garden-fresh and deliciously healthy option that's perfect for any meal! `,
  },
  {
    id: 14,
    title: 'fish and chips with beer',
    category: 'Dinner',
    price: 18.99,
    img:fishandchips,
    desc: `Dive into a mouthwatering experience with our Fish and Chips paired with ice-cold beer - 
    a perfect combination that's sure to satisfy your cravings and quench your thirst! `,
  },
  {
    id: 15,
    title: 'Fruits Salad',
    category: 'Dinner',
    price: 5.99,
    img:fruitSalad,
    desc: `Refresh and revitalize with our Fruit Salad - a colorful and healthy medley of nature's sweetest treats, guaranteed to brighten your day! `,
  },
  {
    id: 16,
    title: 'Hotdogs',
    category: 'Dinner',
    price: 4.99,
    img:hotdog,
    desc: `Bite into a sizzling sensation with our hotdogs - a classic and comforting delight that's perfect for any occasion! `,
  },
  {
    id: 17,
    title: 'Lemon Pudding',
    category: 'Dinner',
    price: 7.99,
    img:lemonPudding,
    desc: `Indulge in a burst of tangy sweetness with our Lemon Pudding - a creamy and refreshing treat that will awaken your taste buds and brighten your day `,
  },
  {
    id: 18,
    title: 'Margeritha Pizza',
    category: 'Dinner',
    price: 15,
    img:margheritaPizza,
    desc: `Savor the simplicity of our Margherita Pizza - a deliciously classic combination of fresh mozzarella, 
    ripe tomatoes, and fragrant basil that's simply irresistible `,
  },
  {
    id: 19,
    title: 'Mexican Tacos',
    category: 'Dinner',
    price: 6.99,
    img:mexicantacos,
    desc: `Spice up your life with our Mexican Tacos - bursting with bold and authentic flavors that will transport your taste buds south of the border! `,
  },
  {
    id: 20,
    title: 'Pasta',
    category: 'Dinner',
    price: 5.99,
    img:pasta,
    desc: `Get tangled up in flavor with our pasta - a hearty and comforting dish that will leave you feeling satisfied and content! `,
  },
  {
    id: 21,
    title: 'Pepperoni Pizza',
    category: 'Dinner',
    price: 17.99,
    img:pepperonipizza,
    desc: `Get a slice of heaven with our classic Pepperoni Pizza - oozing with melted cheese and topped with zesty pepperoni, it's a timeless favorite `,
  },
  {
    id: 22,
    title: 'Ranch Pork Roast',
    category: 'Dinner',
    price: 19.99,
    img:ranchporkroast,
    desc: `Satisfy your cravings with our tangy Ranch Pork Roast - juicy and tender, it's a flavor explosion in every bite! `,
  },
  {
    id: 23,
    title: 'Steak',
    category: 'Dinner',
    price: 25.99,
    img:steak,
    desc: `Juicy, tender, and oh-so-satisfying - our steak is a cut above the rest! `,
  },
  {
    id: 24,
    title: 'Lemon rosemary Salmon',
    category: 'Dinner',
    price: 15.99,
    img:lemonrosemary,
    desc: `Succulent salmon meets zesty lemon and fragrant rosemary - a match made in culinary heaven! `,
  },
  {
    id: 25,
    title: 'Chicken Tacos',
    category: 'Lunch',
    price: 5.99,
    img:chickenTacos,
    desc: `Fiery chicken, fresh fixings, warm tortilla - our Chicken Tacos pack a flavor punch in every bite! `,
  },
  {
    id: 26,
    title: 'California Roll',
    category: 'Lunch',
    price: 14.99,
    img:californiaroll,
    desc: `Roll with the taste of the West Coast with our California Roll - a fusion of creamy avocado, delicate crab meat, 
    crunchy cucumber, and fragrant sesame seeds, all wrapped in a sheet of tender sushi rice and seaweed. 
    It's a delicious and healthy twist on traditional sushi that will have you feeling like you're soaking up the sun on a sunny California beach! `,
  },
  {
    id: 27,
    title: 'Bruschetta',
    category: 'Lunch',
    price: 8.99,
    img:bruschetta,
    desc: `Experience a taste of Italy with every bite of our Bruschetta - a crispy baguette topped with juicy tomatoes, 
    fresh basil, garlic, and drizzled with extra virgin olive oil. It's a burst of Mediterranean flavors that will transport 
    your taste buds straight to the sun-kissed vineyards of Tuscany! `,
  },
  {
    id: 28,
    title: 'Buffalo Wings',
    category: 'Lunch',
    price: 18.99,
    img:buffalowings,
    desc: `"Get ready to wing it with our Buffalo Wings - a spicy and savory explosion of flavor that will leave you licking your fingers 
    and wanting more! Juicy and tender chicken wings tossed in fiery hot sauce, served with cool and creamy blue cheese dressing - 
    it's a flavor-packed party in your mouth `,
  },
  {
    id: 29,
    title: 'Cobb Salad',
    category: 'Lunch',
    price: 10.99,
    img:cobbsalad,
    desc: `Take your taste buds on a delicious journey with our Cobb Salad - a colorful and hearty mix of crisp lettuce, 
    juicy tomatoes, tender chicken, creamy avocado, tangy blue cheese, and all the fixings that will make you fall in love with salads 
    all over again! `,
  },
  {
    id: 30,
    title: 'Key Lime Pie',
    category: 'Lunch',
    price: 13.99,
    img:keylimepie,
    desc: `Indulge in a slice of sunshine with our Key Lime Pie - a zesty and tangy explosion of flavor that will 
    transport your taste buds to a tropical paradise and leave you feeling refreshed, revitalized, and absolutely delighted! `,
  },
  {
    id: 31,
    title: 'Lasagana',
    category: 'Lunch',
    price: 15.99,
    img:lasagana,
    desc: `Experience a slice of Italy with our Lasagna - a hearty and comforting dish of perfectly layered pasta, 
    savory meat sauce, velvety cheese, and aromatic herbs that will have you saying 'mamma mia' with every bite and 
    leave you feeling warm and satisfied inside `,
  },
  {
    id: 32,
    title: 'Steak Fajitas',
    category: 'Lunch',
    price: 20.99,
    img:steakfajita,
    desc: `Get ready to sizzle with our Steak Fajitas - a mouthwatering medley of juicy, tender steak, 
    colorful peppers and onions, zesty spices, and all the fixings that will transport your taste buds to a 
    fiesta of flavors and leave you craving for more! `,
  },
  {
    id: 33,
    title: 'Veg Tacos',
    category: 'Lunch',
    price: 2.99,
    img:vegtacos,
    desc: `Indulge in a burst of colorful and fresh flavors with our Veggie Tacos - 
    a plant-powered feast of crunchy veggies, zesty seasonings, and a hint of spice that will take your taste buds on a delicious and 
    guilt-free ride to taco heaven `,
  },
  {
    id: 34,
    title: 'Expresso',
    category: 'Drinks',
    price: 2.99,
    img:expresso,
    desc: `Take a break from the hustle and bustle of life and enjoy a bold and robust shot of espresso - 
    a powerful and invigorating pick-me-up that will rev up your energy levels and get you ready to conquer anything that comes your way! `,
  },
  {
    id: 35,
    title: 'Latte',
    category: 'Drinks',
    price: 2,
    img:latte,
    desc: `Get ready to cozy up and indulge in a creamy, dreamy, and oh-so-delicious latte - 
    a perfect blend of rich espresso, frothy milk, and a hint of sweetness that will awaken your senses and 
    leave you feeling like you're lounging in a chic café, no matter where you are! `,
  },
  {
    id: 36,
    title: 'Strawberry Smoothie',
    category: 'Drinks',
    price: 6.99,
    img:strawberry,
    desc: `Experience the sweet taste of summer all year round with our Strawberry Smoothie - 
    a refreshing blend of plump and juicy strawberries, velvety smooth yogurt, and 
    a touch of honey that will have you sipping and smiling with every sip! `,
  },
  {
    id: 37,
    title: 'Blue Berry Smoothie',
    category: 'Drinks',
    price: 5.99,
    img:blueberry,
    desc: `Take your taste buds on a wild and delicious ride with our Blueberry Smoothie - 
    a burst of juicy and antioxidant-rich blueberries blended with creamy yogurt, 
    fresh fruit, and a splash of sweetness that will leave you feeling berry-licious all day long! `,
  },
  {
    id: 38,
    title: 'Avacado Smoothie',
    category: 'Drinks',
    price: 7.99,
    img:avacado,
    desc: `Get ready to fuel your body with a healthy dose of green goodness with our Avocado Smoothie - 
    a silky smooth blend of nutrient-dense avocados, refreshing ingredients, and 
    a touch of citrus that will leave you feeling nourished and invigorated from the inside out! `,
  },
  {
    id: 39,
    title: 'Kiwi Smoothie',
    category: 'Drinks',
    price: 7.99,
    img:kiwi,
    desc: `"Experience a taste of paradise with our Kiwi Smoothie - 
    a luscious blend of sweet and tangy flavors that will transport your taste buds to a tropical oasis!" `,
  },
  {
    id: 40,
    title: 'Banana Smoothie',
    category: 'Drinks',
    price: 4.99,
    img:banana,
    desc: `Start your day off with a bang and power up your mornings with our Banana Smoothie - 
    a creamy and delicious blend of potassium-rich bananas, wholesome ingredients, and 
    a hint of sweetness that will keep you energized all day long `,
  },
  {
    id: 41,
    title: 'Dragon Fruit Smoothie',
    category: 'Drinks',
    price: 6.99,
    img:dragonfruit,
    desc: `"Indulge in a fiery blend of tropical sweetness with our Dragon Fruit Smoothie - 
    a refreshing burst of vibrant pink goodness packed with exotic flavors and nourishing goodness!" `,
  },
];
export default Dishes;